version: '2'
services:
  dev:
    image: 642631414762.dkr.ecr.eu-west-1.amazonaws.com/frontend-dev:latest
    command: bash
    ports: 
        - "9000:9000"
    working_dir: /frontend
    volumes:
        - .:/frontend
        - ~/.gu:/root/.gu
        - ~/.aws:/root/.aws
        # We don't currently use mounted cache directories
        # because performance on Docker for Mac are aweful for now (Aug 2016)
        # To mitigate the issue with populating the caches, 
        # the project is built once during the image building process
        # Mount cache directories
        #- ~/.npm:/root/.npm
        #- ~/.sbt:/root/.sbt
        #- ~/.ivy2:/root/.ivy2
